### ISSUE TITLE
Consistant Naming

### ISSUE THREAD

**Issue by mikkoh** [noflo/noflo-math#3]
This is not an issue but a topic of discussion.

The in ports on all of the math components are named after mathematical terms:
- minuend and subtrahend
- augend and addend
- dividend and divisor

I'm just wondering what was the thought process behind the naming convention? If in some sense the hope is for FBP to be used by "high level" programmers ideally the terms should be basic.

If all of the in ports were simply named leftSide and rightSide it would be consistent across all math components and it would be very understandable for just about anyone.

Not trying to troll but just wondering about this. Obviously this could be annoying to refactor as it may effect quite a few applications.

**Comment by ensonic** [comment]
Maybe ports can have aliases. That could also help with legacy names.
